// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// search_pairs
NumericMatrix search_pairs(IntegerMatrix clusterings);
RcppExport SEXP _clusterExperiment_search_pairs(SEXP clusteringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type clusterings(clusteringsSEXP);
    rcpp_result_gen = Rcpp::wrap(search_pairs(clusterings));
    return rcpp_result_gen;
END_RCPP
}
// do_seq_cluster
List do_seq_cluster(arma::mat x, arma::mat diss, int N, int k0, int remain_n, int seq_num, int k_min, int k_max, int top_can, int beta, IntegerMatrix index_m, String beta_num, int wh_return, String input, Function updateClustering);
RcppExport SEXP _clusterExperiment_do_seq_cluster(SEXP xSEXP, SEXP dissSEXP, SEXP NSEXP, SEXP k0SEXP, SEXP remain_nSEXP, SEXP seq_numSEXP, SEXP k_minSEXP, SEXP k_maxSEXP, SEXP top_canSEXP, SEXP betaSEXP, SEXP index_mSEXP, SEXP beta_numSEXP, SEXP wh_returnSEXP, SEXP inputSEXP, SEXP updateClusteringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type diss(dissSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type k0(k0SEXP);
    Rcpp::traits::input_parameter< int >::type remain_n(remain_nSEXP);
    Rcpp::traits::input_parameter< int >::type seq_num(seq_numSEXP);
    Rcpp::traits::input_parameter< int >::type k_min(k_minSEXP);
    Rcpp::traits::input_parameter< int >::type k_max(k_maxSEXP);
    Rcpp::traits::input_parameter< int >::type top_can(top_canSEXP);
    Rcpp::traits::input_parameter< int >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type index_m(index_mSEXP);
    Rcpp::traits::input_parameter< String >::type beta_num(beta_numSEXP);
    Rcpp::traits::input_parameter< int >::type wh_return(wh_returnSEXP);
    Rcpp::traits::input_parameter< String >::type input(inputSEXP);
    Rcpp::traits::input_parameter< Function >::type updateClustering(updateClusteringSEXP);
    rcpp_result_gen = Rcpp::wrap(do_seq_cluster(x, diss, N, k0, remain_n, seq_num, k_min, k_max, top_can, beta, index_m, beta_num, wh_return, input, updateClustering));
    return rcpp_result_gen;
END_RCPP
}
// makeHashKey
std::string makeHashKey(int i, int j, std::string delim);
RcppExport SEXP _clusterExperiment_makeHashKey(SEXP iSEXP, SEXP jSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< std::string >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(makeHashKey(i, j, delim));
    return rcpp_result_gen;
END_RCPP
}
// splitHashKey
Rcpp::IntegerVector splitHashKey(std::string s, std::string delim);
RcppExport SEXP _clusterExperiment_splitHashKey(SEXP sSEXP, SEXP delimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    Rcpp::traits::input_parameter< std::string >::type delim(delimSEXP);
    rcpp_result_gen = Rcpp::wrap(splitHashKey(s, delim));
    return rcpp_result_gen;
END_RCPP
}
// subsampleLoop
Rcpp::IntegerMatrix subsampleLoop(Rcpp::List clList, int N);
RcppExport SEXP _clusterExperiment_subsampleLoop(SEXP clListSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type clList(clListSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(subsampleLoop(clList, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clusterExperiment_search_pairs", (DL_FUNC) &_clusterExperiment_search_pairs, 1},
    {"_clusterExperiment_do_seq_cluster", (DL_FUNC) &_clusterExperiment_do_seq_cluster, 15},
    {"_clusterExperiment_makeHashKey", (DL_FUNC) &_clusterExperiment_makeHashKey, 3},
    {"_clusterExperiment_splitHashKey", (DL_FUNC) &_clusterExperiment_splitHashKey, 2},
    {"_clusterExperiment_subsampleLoop", (DL_FUNC) &_clusterExperiment_subsampleLoop, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_clusterExperiment(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
